version: '3.8'
services:
  radraffle-redis:
    container_name: raffle-redis
    restart: unless-stopped
    image: redis
  radraffle-sql:
    container_name: raffle-postgres
    restart: unless-stopped
    image: postgres
    volumes:
      - "raffle_postgres:/var/lib/postgresql/data"
    env_file:
      "/opt/appsettings/envir/raffle.env"
  radicitus-raffle:
    container_name: radicitus-raffle
    restart: unless-stopped
    image: radicitus-raffle:1.0
    ports:
      - "8080:5000"
    volumes:
      - "raffle_appsettings:/opt/appsettings/radicitus-raffle"
    depends_on:
      - radraffle-sql
      - radraffle-redis
volumes:
  raffle_postgres:
  raffle_appsettings: