// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Radicitus.Data.Contexts.Raffles;

namespace Radicitus.Raffle.Migrations
{
    [DbContext(typeof(RadicitusDbContext))]
    [Migration("20201115195825_ForeignKeyFix")]
    partial class ForeignKeyFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rad")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Radicitus.Data.Contexts.Raffles.Entities.RadRaffle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<decimal?>("AmountWon")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_won");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_created_utc");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date_utc");

                    b.Property<string>("RaffleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("raffle_name");

                    b.Property<decimal>("SquareWorthAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("square_worth_amount");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date_utc");

                    b.Property<string>("WinnerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("winner_name");

                    b.Property<int?>("WinningSquare")
                        .HasColumnType("integer")
                        .HasColumnName("winning_square");

                    b.HasKey("Id");

                    b.ToTable("rad_raffle");
                });

            modelBuilder.Entity("Radicitus.Data.Contexts.Raffles.Entities.RaffleNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("RaffleId")
                        .HasColumnType("integer")
                        .HasColumnName("raffle_id");

                    b.HasKey("Id");

                    b.HasIndex("RaffleId");

                    b.ToTable("raffle_number");
                });

            modelBuilder.Entity("Radicitus.Data.Contexts.Raffles.Entities.RaffleNumber", b =>
                {
                    b.HasOne("Radicitus.Data.Contexts.Raffles.Entities.RadRaffle", "Raffle")
                        .WithMany("RaffleNumbers")
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raffle");
                });

            modelBuilder.Entity("Radicitus.Data.Contexts.Raffles.Entities.RadRaffle", b =>
                {
                    b.Navigation("RaffleNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
